FROM python:3.11-slim

RUN useradd -m judge && mkdir -p /judge && chown judge:judge /judge
COPY judge_service/scripts/judge_python.py /usr/local/bin/judge.py

USER judge
WORKDIR /judge

ENTRYPOINT ["python", "/usr/local/bin/judge.py"]
